### PR TITLE
resolved issue https://github.com/Azure/azure-xplat-cli/issues/1763

### PR DESCRIPTION
**Pull request by MikhailTryakhov**
reworked sub-lb elements show commands in json format

### CODE REVIEW

**Comment by anuchandy** [comment]
thanks you @MikhailTryakhov , Please don't merge this now. I have few worries about our implementation about this. I have requested @babumuralidharan and @HimanshuBri to verify this your on your branch https://github.com/Azure/azure-xplat-cli/issues/1763. I am discussion the test scenario with @babumuralidharan

**Comment by MikhailTryakhov** [comment]
Hi @anuchandy, @babumuralidharan, are there any updates here? this PR would be very helpful for arm show functionality

**Comment by HimanshuBri** [comment]
@MikhailTryakhov . Please refer https://github.com/Azure/azure-xplat-cli/issues/1763

**Comment by MikhailTryakhov** [comment]
@anuchandy  please approve that it should be merged. Issue is closed now and another  one is opened [here](https://github.com/MSOpenTech/azure-xplat-cli/issues/193). That would be great to merge it and not to raise issue list

**Comment by anuchandy** [comment]
@MikhailTryakhov sorry for the delay in responding. My main concern was related to passing 'interaction' reference to our ShowUtil classes, thought of keeping showUtil as loosely coupled as possible. We want to ensure we pass only output as an input param.

Since we need to send a final PR tomorrow and finish the test pass today, I am making required changes  and sending a PR here https://github.com/MSOpenTech/azure-xplat-cli/pull/198

I am closing this PR.

**Pull request closed without merging**
