### PR TITLE
Fixed Azure bug 1781.

### PR DESCRIPTION
**Pull request by roman-boltunov**
* Removed 'Record1, Record2, etc..' on each line of actual record data.
* Changed labels to exact same terminology as in CloudDNS.

### CODE REVIEW

**Comment by anuchandy** [comment]
@roman-boltunov Please wait Jonathan to reply, before we merge this https://github.com/Azure/azure-xplat-cli/issues/1781

**Comment by anuchandy** [comment]
@roman-boltunov please wait for Jonathan to confirm the 'readable names' we use. We just shared it with him here https://github.com/Azure/azure-xplat-cli/issues/1781

Also another point: just noticed that in show section where we output 'srvRecord', we access the target property like "srvRecord.Target", usually js property name start with lower char, please confirm whether SDK is creating property like srvRecord.Target instead of srvRecord.target.or we missed it

**Comment by roman-boltunov** [comment]
@anuchandy good catch! Actually the property named 'target', that was my mistake to name it 'Target'.

**Comment by anuchandy** [comment]
@roman-boltunov Thank you LGTM

**Pull request merged**
