### PR TITLE
Network ASM: shared-key, vpn-devices, diagnositcs commands implemented.

### PR DESCRIPTION
**Pull request by roman-boltunov**
This PR contains:
* shared-key commands: set, reset
* vpn-devices commands: list, get-script
* diagnostics commands: start, stop, get
* resolved minor 'nsg rule' issues 

**Please note, the following commands is not finished yet:**
* vpn-devices get-script
* diagnostics stop

### CODE REVIEW

**Comment by anuchandy** [comment]
Thanks @roman-boltunov  LGTM

**Comment by roman-boltunov** [comment]
Hi @anuchandy. 'vpn-devices get-script' command still not working, should I merge this PR?

**Comment by anuchandy** [comment]
@roman-boltunov 

Have you tried fetching script for a virtual network for which we have vpn gateway configured? If i am not wrong i think we tried to fetch the script for simple virtual network.

**Comment by roman-boltunov** [comment]
@anuchandy I tried, in fact it works on portal. For portal, generated URL differs from the SDK, it uses ARM API.
For example:
```
SDK
https://management.core.windows.net/5893435f-6990-4bb3-bebb-b12f3535f990/services/networking/rom-vnet1/gateway/vpndeviceconfigurationscript?vendor=Microsoft%20Corporation&platform=RRAS&OSfamily=Windows%20Server%202012
```

```
PORTAL
https://management.azure.com/subscriptions/5893435f-6990-4bb3-bebb-b12f3535f990/resourceGroups/Default-Networking/providers/Microsoft.ClassicNetwork/virtualNetworks/rom-vnet1/gateways/primary/downloadDeviceConfigurationScript?vendor=Microsoft+Corporation&platform=RRAS&osFamily=Windows+Server+2012&api-version=2014-06-01
```

So I guess it still doesn't  work on ASM SDK.

**Pull request merged**
