### PR TITLE
Fixed Azure bug 1782.

### PR DESCRIPTION
**Pull request by roman-boltunov**
* removed look ups before delete.

### CODE REVIEW

**Comment by anuchandy** [comment]
Please refer comments https://github.com/Azure/azure-xplat-cli/issues/1782

**Comment by roman-boltunov** [comment]
@anuchandy Thanks. Updated PR.

**Comment by roman-boltunov** [comment]
@anuchandy right! Updated this PR.

**Comment by anuchandy** [comment]
@roman-boltunov  thank you. LGTM

**Pull request merged**
