### PR TITLE
Network ASM: application gateway commands.

### PR DESCRIPTION
**Pull request by roman-boltunov**

### CODE REVIEW

**Comment by anuchandy** [comment]
Please test your commands as we have vpn gateway server issue unblocked. Please let me know once it is verified and done with code change, we can review and get this in.

**Comment by roman-boltunov** [comment]
Hi @anuchandy.
I've added SSL commands, tested application gateway commands and found following issues:
1. 'ssl-cert add' throws error in both scenarios (success, error). **error: object is not a function**. This might be a SDK issue, since with -vv output I can see success or fail result with proper information.
2. start and stop commands is not tested yet since they are asking for configuration:
**error:   No configuration is set on the gateway. Configuration must be set before gateway could be started.**. Will ping you later about this when configuration commands will be tested and available.
3. Minor issue - all commands executes too long. For example 'ssl-cert add' command executes for 15-25 minutes. Is it expected?
4. 'show' command might be changed a little later.

**Comment by anuchandy** [comment]
@roman-boltunov  Thanks you.

ssl-cert add error is definitely SDK we will report this.

@romangromov pointed some issue related to setConfig. I have requested to try following before escalating to server team.

1.	The SDK seems using POST, usually set operation uses PUT. Can we try changing POST to PUT in the SDK? If that works then we will request OneSDK team to update the SDK generation spec otherwise we will inform the server team.
2.	Try setting some value for some fields, for example backendAddressPools = [ { name:<some-name>, backendServers: [<ip-address>]}]
Try with both POST and PUT and see it works. May be server is throwing error due to empty configuration

**Comment by roman-boltunov** [comment]
@anuchandy I tried to set application gateway configuration with 'PUT' and server returns 405 error - Method not allowed, so the issue with setConfig method might be server issue.

**Comment by romangromov** [comment]
Hi @anuchandy and @roman-boltunov 

1. POST replaced with PUT: no luck, getting `405 Method not allowed` error response

**Pull request merged**
