### PR TITLE
Remove multi Vip check

### PR DESCRIPTION
**Pull request by DeepakRajendranMsft**
@babumuralidharan I have removed this check. However I am not sure if this is the only place where this change needs to happen. Please add tests. Feel remove to remove other checks if present.

@anuchandy  as FYI

### CODE REVIEW

**Comment by babumuralidharan** [comment]
@MikhailTryakhov @romangromov can you guys verify this PR and see if this change is good to go to enable multiVIp? Ignore the merge conflicts as this is a sync issue from upstream. The change is only removing multiVIP check  in loadBalancer_.js.

**Comment by MikhailTryakhov** [comment]
Hi @babumuralidharan  - in my version of SDK there is the same restriction on SDK side - please review screenshot below
error msg
Is this version correct? In this case we can just send such data on the server and result would depend on SDK fucntionality. I think that's good

**Comment by babumuralidharan** [comment]
@MikhailTryakhov I don't think there is any restriction as such. This check we can make it in any stable branch since we are seeing merge conflicts in this PR. 

@MikhailTryakhov, @romangromov is this check removal seems OK ? If yes we can just do the change and include it in dev branch and have a test case written against this? Thoughts??

**Comment by romangromov** [comment]
Hi @babumuralidharan, sorry for delay, this check removal proposed by @DeepakRajendranMsft seems OK, since `dev` branch was merged to `upstream` we can safely include this PR to `dev` branch and implement test cases for this. Please note: I'm currently blocked with `azure login` command so I can't make any smoke testing at first and fix issues after this change will be included

**Comment by DeepakRajendranMsft** [comment]
@babumuralidharan Can we get this change and tests in by this week so we make into this weeks release?

**Comment by babumuralidharan** [comment]
@romangromov let me send a new PR with only this change to dev branch and will merge it since you guys have confirmed this change..closing this PR for now

**Pull request closed without merging**
