### PR TITLE
Network ASM: route-table commands implemented.

### PR DESCRIPTION
**Pull request by roman-boltunov**
This PR contains following: 
* route-table create
* route-table show 
* route-table list
* route-table delete

### CODE REVIEW

**Comment by roman-boltunov** [comment]
@anuchandy thank you for code review. Updated this PR.

**Comment by anuchandy** [comment]
Thank you @roman-boltunov LGTM

**Comment by roman-boltunov** [comment]
Hi @anuchandy. I've updated this PR with 'route-table list' command, also updated 'route-table show' command. Could you please take a look at these updates?

**Comment by anuchandy** [comment]
LGTM, please take a look at above few minor comments.

**Pull request merged**
